# Generated by Django 4.0 on 2021-12-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(default='', verbose_name='Entry')),
                ('rating', models.IntegerField(choices=[(0, 'Bad'), (1, 'Not to bad'), (2, 'Good'), (3, 'Very_good'), (4, 'Fantastic')], default=0, verbose_name='Rating')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.book', verbose_name='Book')),
            ],
        ),
    ]
