# Generated by Django 4.0 on 2021-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_review_date_review_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
