# Generated by Django 4.0 on 2021-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_alter_review_date_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
