# Generated by Django 4.0 on 2021-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Publication year'),
        ),
    ]
