# Generated by Django 4.0 on 2021-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_alter_author_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='entry',
            field=models.TextField(blank=True, null=True, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Bad'), (1, 'Not to bad'), (2, 'Good'), (3, 'Very_good'), (4, 'Fantastic')], verbose_name='Rating'),
        ),
    ]
