# Generated by Django 4.0 on 2021-12-28 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_alter_review_date_review_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date return'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date borrowed'),
        ),
    ]
