# Generated by Django 4.0 on 2022-01-03 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_alter_review_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 20, 15, 18, 233444, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
