# Generated by Django 4.0 on 2022-01-07 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_alter_borrowedbook_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 16, 0, 47, 470183, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
