# Generated by Django 4.0 on 2022-01-21 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import libraries.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0016_book_book_cover_alter_borrowedbook_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Publication year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to='libraries.book', validators=[libraries.models.check_if_borrowed], verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 20, 20, 12, 9, 653472, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
