# Generated by Django 4.0 on 2022-01-25 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0018_alter_borrowedbook_date_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('date_birth',)},
        ),
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ['-date_end']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_review']},
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 10, 52, 14, 984977, tzinfo=utc), verbose_name='Date return'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to='author',
        ),
    ]
