# Generated by Django 4.0 on 2022-01-25 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0019_alter_author_options_alter_borrowedbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ('-date_end',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date_review',)},
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 11, 32, 50, 424333, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
