# Generated by Django 4.0 on 2022-01-25 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0020_alter_borrowedbook_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 13, 8, 3, 381622, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
