# Generated by Django 4.0 on 2022-01-25 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0021_alter_borrowedbook_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 14, 19, 31, 686274, tzinfo=utc), verbose_name='Date return'),
        ),
    ]
